version: "3.3"
services:
  tydal-db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: OneMoreSale69~
      MYSQL_DATABASE: tydal_stevefarmerrealtor
      MYSQL_USER: tydal_wp
      MYSQL_PASSWORD: OneMoreSale69

  tydal-wp:
    depends_on:
      - tydal-db
    build: .
    volumes:
      - ./src:/var/www/html
    links:
      - tydal-db:mysql
    ports:
      - 8000:80
      - 8443:443
    environment:
      WORDPRESS_DB_NAME: tydal_stevefarmerrealtor
      WORDPRESS_DB_USER: tydal_wp
      WORDPRESS_DB_PASSWORD: OneMoreSale69

  tydal-phpmyadmin:
    depends_on:
      - tydal-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_HOST: tydal-db
      MYSQL_ROOT_PASSWORD: OneMoreSale69~
